vscode:
  extensions:
    - ritwickdey.LiveServer@5.6.1:5Mhl1RgVVDcIym163x8r+w==
    - Zignd.html-css-class-completion@1.19.0:Soyzg8syqQX3vm86CKnPtg==
    - abusaidm.html-snippets@0.2.1:HrYIjYqOIABbxFB9g9kqXQ==
    - ecmel.vscode-html-css@0.2.3:hh8R73s3n0g/eQ8EL9PatQ==
    - formulahendry.auto-close-tag@0.5.7:ofk2Iz4wGQdoTFrnRwzI7w==